package com.ashasaathi.ui.strings

import androidx.compose.runtime.Composable
import com.ashasaathi.ui.LocalAppLanguage

data class AppStrings(
    // Common
    val save: String,
    val cancel: String,
    val close: String,
    val offline: String,
    val years: String,

    // Home
    val homeMetricVisits: String,
    val homeMetricHighRisk: String,
    val homeMetricVaccines: String,
    val homeMetricDots: String,
    val homeTotalHouseholds: String,
    val homeTotalPatients: String,
    val homeTotalVisitsMonth: String,
    val homeHighRiskAlert: String,        // use String.format with count
    val homeWorkplanTitle: String,
    val homeAllGood: String,
    val homeVoiceLabel: String,
    val homeVoiceSub: String,
    val homeQuickActions: String,
    val homeAddFamily: String,
    val homeViewMap: String,
    val homeMonthlyReport: String,
    val homeDotsTracker: String,
    val tagPregnant: String,
    val tagChild: String,
    val tagElderly: String,

    // Households
    val householdsTitle: String,
    val householdsSearch: String,
    val householdsEmpty: String,
    val householdsAdd: String,

    // Vaccination
    val vaccinationTitle: String,
    val vaccineFIC: String,               // use String.format with count
    val vaccineDueTab: String,
    val vaccineMissedTab: String,
    val vaccineAllTab: String,
    val vaccineEmpty: String,
    val vaccineAgeLabel: String,          // use String.format with age
    val vaccineGiven: String,
    val vaccineGiveToday: String,
    val vaccineMissedDays: String,        // use String.format with days
    val vaccineUpcoming: String,
    val vaccineMarkGiven: String,

    // Planner
    val plannerTitle: String,
    val plannerEmpty: String,
    val plannerSubtitle: String,          // use String.format with count
    val plannerVisitDone: String,

    // Patient Detail
    val patientPersonalInfo: String,
    val patientName: String,
    val patientAge: String,
    val patientGender: String,
    val patientPhone: String,
    val patientPregnancy: String,
    val patientTBDots: String,
    val patientVisitHistory: String,
    val patientNoVisits: String,
    val patientReferralNeeded: String,

    // Visit Form
    val visitTitle: String,
    val visitVitals: String,
    val visitWeight: String,
    val visitTemp: String,
    val visitPregnancy: String,
    val visitIfaToday: String,
    val visitFastingGlucose: String,
    val visitIfaProgress: String,         // use String.format with count
    val visitSymptoms: String,
    val visitFever: String,
    val visitCoughDays: String,
    val visitNotes: String,
    val visitNotesHint: String,
    val visitReferral: String,
    val visitReferralReason: String,
    val visitSave: String,
    val visitNoRisk: String,
    val visitOk: String,

    // TB DOTS
    val tbTitle: String,
    val tbEmpty: String,
    val tbDotsDue: String,
    val tbDotsGiven: String,
    val tbDotsRecord: String,
    val tbCalendar: String,
    val tbCalendarTitle: String,
    val tbClose: String,

    // Diary
    val diaryTitle: String,
    val diaryEmpty: String,
    val diaryNewEntry: String,
    val diaryHint: String,
    val diarySave: String,
    val diaryCancel: String,

    // Reports
    val reportsTitle: String,
    val reportsPdfDownload: String,
    val reportsCoverage: String,
    val reportsTotalHouseholds: String,
    val reportsTotalPatients: String,
    val reportsVisitsMonth: String,
    val reportsANC: String,
    val reportsPregnant: String,
    val reportsANC1st: String,
    val reportsANC4Plus: String,
    val reportsTT: String,
    val reportsIFA180: String,
    val reportsHighRisk: String,
    val reportsInstitutional: String,
    val reportsImmunisation: String,
    val reportsUnder5: String,
    val reportsFIC: String,
    val reportsFICPercent: String,
    val reportsCIC: String,
    val reportsVaccineDueToday: String,
    val reportsVaccineMissed: String,
    val reportsTB: String,
    val reportsTBRegistered: String,
    val reportsDOTSGood: String,
    val reportsDOTSPoor: String,
    val reportsDBT: String,
    val reportsSchemes: String,
    val reportsJSY: String,
    val reportsPMMVY: String,
    val reportsNHMActivities: String,

    // Settings
    val settingsTitle: String,
    val settingsLanguageSection: String,
    val settingsAppLanguage: String,
    val settingsVoiceModels: String,
    val settingsAppInfo: String,
    val settingsLogout: String,
    val settingsLogoutTitle: String,
    val settingsLogoutMsg: String,
    val settingsLogoutYes: String,
    val settingsSelectLanguage: String,
    val settingsCloseBtn: String,
)

// ── Hindi ─────────────────────────────────────────────────────────────────────

private val Hindi = AppStrings(
    save = "सेव करें",
    cancel = "रद्द करें",
    close = "बंद करें",
    offline = "ऑफलाइन — डेटा सेव है",
    years = "वर्ष",

    homeMetricVisits = "आज की\nविजिट",
    homeMetricHighRisk = "उच्च\nजोखिम",
    homeMetricVaccines = "टीके\nबाकी",
    homeMetricDots = "DOTS\nबाकी",
    homeTotalHouseholds = "परिवार",
    homeTotalPatients = "मरीज़",
    homeTotalVisitsMonth = "इस माह",
    homeHighRiskAlert = "⚠️ %d उच्च जोखिम — पहले मिलें",
    homeWorkplanTitle = "आज का कार्यक्रम",
    homeAllGood = "आज सब ठीक है!",
    homeVoiceLabel = "🎤  आवाज़ से दर्ज करें",
    homeVoiceSub = "परिवार · मरीज़ · ANC · टीका · DOTS",
    homeQuickActions = "त्वरित कार्य",
    homeAddFamily = "🏠\nपरिवार जोड़ें",
    homeViewMap = "🗺️\nनक्शा देखें",
    homeMonthlyReport = "📋\nमासिक रिपोर्ट",
    homeDotsTracker = "💊\nDOTS ट्रैकर",
    tagPregnant = "🤰 गर्भवती",
    tagChild = "👶 शिशु",
    tagElderly = "👴 वृद्ध",

    householdsTitle = "घर-परिवार",
    householdsSearch = "खोजें...",
    householdsEmpty = "कोई परिवार नहीं",
    householdsAdd = "परिवार जोड़ें",

    vaccinationTitle = "टीकाकरण ट्रैकर",
    vaccineFIC = "✅ FIC: %d बच्चे",
    vaccineDueTab = "आज बाकी",
    vaccineMissedTab = "छूटे",
    vaccineAllTab = "सभी",
    vaccineEmpty = "कोई टीका बाकी नहीं",
    vaccineAgeLabel = "उम्र: %d वर्ष",
    vaccineGiven = "✅ दिया गया",
    vaccineGiveToday = "⚡ आज दें",
    vaccineMissedDays = "⚠️ छूटा (%d दिन)",
    vaccineUpcoming = "📅 आगे",
    vaccineMarkGiven = "दिया",

    plannerTitle = "आज का प्लानर",
    plannerEmpty = "आज कोई विजिट नहीं",
    plannerSubtitle = "%d विजिट • पहले लाल, फिर पीले",
    plannerVisitDone = "✅ विजिट हुई",

    patientPersonalInfo = "व्यक्तिगत जानकारी",
    patientName = "नाम / Name",
    patientAge = "उम्र / Age",
    patientGender = "लिंग / Gender",
    patientPhone = "फोन / Phone",
    patientPregnancy = "🤰 गर्भावस्था",
    patientTBDots = "💊 TB / DOTS",
    patientVisitHistory = "विजिट इतिहास",
    patientNoVisits = "कोई विजिट नहीं",
    patientReferralNeeded = "⚠️ रेफरल जरूरी",

    visitTitle = "विजिट दर्ज करें",
    visitVitals = "वाइटल्स / Vitals",
    visitWeight = "वजन / Weight (kg)",
    visitTemp = "तापमान / Temp (°C)",
    visitPregnancy = "🤰 गर्भावस्था विवरण",
    visitIfaToday = "IFA आज दिए",
    visitFastingGlucose = "फास्टिंग शुगर",
    visitIfaProgress = "IFA प्रगति: %d / 180",
    visitSymptoms = "लक्षण / Symptoms",
    visitFever = "बुखार / Fever",
    visitCoughDays = "खांसी के दिन / Cough Days",
    visitNotes = "नोट्स / Clinical Notes",
    visitNotesHint = "माइक बटन दबाकर बोलें या यहाँ लिखें...",
    visitReferral = "रेफरल जरूरी / Referral Needed",
    visitReferralReason = "रेफरल कारण / Reason",
    visitSave = "विजिट सेव करें / Save Visit",
    visitNoRisk = "कोई जोखिम नहीं मिला।",
    visitOk = "ठीक है / OK",

    tbTitle = "TB DOTS ट्रैकर",
    tbEmpty = "कोई TB मरीज नहीं",
    tbDotsDue = "⚠️ आज DOTS बाकी है",
    tbDotsGiven = "✅ DOTS ले लिया",
    tbDotsRecord = "DOTS दर्ज करें",
    tbCalendar = "कैलेंडर",
    tbCalendarTitle = "DOTS कैलेंडर",
    tbClose = "बंद करें",

    diaryTitle = "मेरी डायरी",
    diaryEmpty = "डायरी में कुछ लिखें",
    diaryNewEntry = "नई एंट्री / New Entry",
    diaryHint = "आज के बारे में लिखें...",
    diarySave = "सेव करें",
    diaryCancel = "रद्द करें",

    reportsTitle = "मासिक रिपोर्ट",
    reportsPdfDownload = "PDF डाउनलोड करें",
    reportsCoverage = "कार्यक्षेत्र सारांश",
    reportsTotalHouseholds = "कुल परिवार",
    reportsTotalPatients = "कुल मरीज",
    reportsVisitsMonth = "इस माह विजिट",
    reportsANC = "ANC सेवाएँ",
    reportsPregnant = "गर्भवती महिलाएं",
    reportsANC1st = "ANC पंजीकृत (1st Trimester)",
    reportsANC4Plus = "4+ ANC प्राप्त",
    reportsTT = "TT2 / Booster दिया",
    reportsIFA180 = "IFA 180 पूर्ण",
    reportsHighRisk = "उच्च जोखिम (RED)",
    reportsInstitutional = "संस्थागत प्रसव",
    reportsImmunisation = "UIP टीकाकरण",
    reportsUnder5 = "5 वर्ष से कम बच्चे",
    reportsFIC = "FIC (पूर्ण टीकाकरण)",
    reportsFICPercent = "FIC % (लक्ष्य 90%)",
    reportsCIC = "CIC (पूर्ण श्रेणी)",
    reportsVaccineDueToday = "आज टीका बाकी",
    reportsVaccineMissed = "छूटे टीके",
    reportsTB = "TB DOTS / क्षय रोग",
    reportsTBRegistered = "TB मरीज पंजीकृत",
    reportsDOTSGood = "DOTS अनुपालन ≥90%",
    reportsDOTSPoor = "DOTS अनुपालन <70%",
    reportsDBT = "DBT इस माह",
    reportsSchemes = "सरकारी योजनाएँ",
    reportsJSY = "JSY लाभार्थी",
    reportsPMMVY = "PMMVY लाभार्थी",
    reportsNHMActivities = "NHM गतिविधियाँ",

    settingsTitle = "सेटिंग्स",
    settingsLanguageSection = "भाषा / Language",
    settingsAppLanguage = "ऐप भाषा / App Language",
    settingsVoiceModels = "आवाज़ मॉडल / Voice Models",
    settingsAppInfo = "ऐप जानकारी / App Info",
    settingsLogout = "लॉगआउट / Logout",
    settingsLogoutTitle = "लॉगआउट?",
    settingsLogoutMsg = "क्या आप वाकई लॉगआउट करना चाहते हैं?",
    settingsLogoutYes = "हाँ, लॉगआउट करें",
    settingsSelectLanguage = "भाषा चुनें / Select Language",
    settingsCloseBtn = "बंद करें",
)

// ── English ───────────────────────────────────────────────────────────────────

private val English = AppStrings(
    save = "Save",
    cancel = "Cancel",
    close = "Close",
    offline = "Offline — data saved locally",
    years = "yrs",

    homeMetricVisits = "Today's\nVisits",
    homeMetricHighRisk = "High\nRisk",
    homeMetricVaccines = "Vaccines\nDue",
    homeMetricDots = "DOTS\nDue",
    homeTotalHouseholds = "Families",
    homeTotalPatients = "Patients",
    homeTotalVisitsMonth = "This Month",
    homeHighRiskAlert = "⚠️ %d high risk — visit first",
    homeWorkplanTitle = "Today's Workplan",
    homeAllGood = "All clear today!",
    homeVoiceLabel = "🎤  Voice Entry",
    homeVoiceSub = "Household · Patient · ANC · Vaccine · DOTS",
    homeQuickActions = "Quick Actions",
    homeAddFamily = "🏠\nAdd Family",
    homeViewMap = "🗺️\nView Map",
    homeMonthlyReport = "📋\nMonthly Report",
    homeDotsTracker = "💊\nDOTS Tracker",
    tagPregnant = "🤰 Pregnant",
    tagChild = "👶 Child",
    tagElderly = "👴 Elderly",

    householdsTitle = "Households",
    householdsSearch = "Search...",
    householdsEmpty = "No households yet",
    householdsAdd = "Add Household",

    vaccinationTitle = "Vaccination Tracker",
    vaccineFIC = "✅ FIC: %d children",
    vaccineDueTab = "Due Today",
    vaccineMissedTab = "Missed",
    vaccineAllTab = "All",
    vaccineEmpty = "No vaccines due",
    vaccineAgeLabel = "Age: %d yrs",
    vaccineGiven = "✅ Given",
    vaccineGiveToday = "⚡ Give Today",
    vaccineMissedDays = "⚠️ Missed (%d days)",
    vaccineUpcoming = "📅 Upcoming",
    vaccineMarkGiven = "Mark Given",

    plannerTitle = "Today's Planner",
    plannerEmpty = "No visits today",
    plannerSubtitle = "%d visits · Red first, then yellow",
    plannerVisitDone = "✅ Visited",

    patientPersonalInfo = "Personal Info",
    patientName = "Name",
    patientAge = "Age",
    patientGender = "Gender",
    patientPhone = "Phone",
    patientPregnancy = "🤰 Pregnancy",
    patientTBDots = "💊 TB / DOTS",
    patientVisitHistory = "Visit History",
    patientNoVisits = "No visits recorded",
    patientReferralNeeded = "⚠️ Referral Needed",

    visitTitle = "Record Visit",
    visitVitals = "Vitals",
    visitWeight = "Weight (kg)",
    visitTemp = "Temperature (°C)",
    visitPregnancy = "🤰 Pregnancy Details",
    visitIfaToday = "IFA tablets today",
    visitFastingGlucose = "Fasting glucose",
    visitIfaProgress = "IFA progress: %d / 180",
    visitSymptoms = "Symptoms",
    visitFever = "Fever",
    visitCoughDays = "Cough days",
    visitNotes = "Clinical Notes",
    visitNotesHint = "Press mic or type here...",
    visitReferral = "Referral Needed",
    visitReferralReason = "Referral Reason",
    visitSave = "Save Visit",
    visitNoRisk = "No risk factors found.",
    visitOk = "OK",

    tbTitle = "TB DOTS Tracker",
    tbEmpty = "No TB patients",
    tbDotsDue = "⚠️ DOTS due today",
    tbDotsGiven = "✅ DOTS taken",
    tbDotsRecord = "Record DOTS",
    tbCalendar = "Calendar",
    tbCalendarTitle = "DOTS Calendar",
    tbClose = "Close",

    diaryTitle = "My Diary",
    diaryEmpty = "Write something in your diary",
    diaryNewEntry = "New Entry",
    diaryHint = "Write about today...",
    diarySave = "Save",
    diaryCancel = "Cancel",

    reportsTitle = "Monthly Report",
    reportsPdfDownload = "Download PDF",
    reportsCoverage = "Coverage Summary",
    reportsTotalHouseholds = "Total Households",
    reportsTotalPatients = "Total Patients",
    reportsVisitsMonth = "Visits This Month",
    reportsANC = "ANC Services",
    reportsPregnant = "Pregnant Women",
    reportsANC1st = "ANC Registered (1st Trimester)",
    reportsANC4Plus = "4+ ANC Received",
    reportsTT = "TT2 / Booster Given",
    reportsIFA180 = "IFA 180 Complete",
    reportsHighRisk = "High Risk (RED)",
    reportsInstitutional = "Institutional Deliveries",
    reportsImmunisation = "UIP Immunisation",
    reportsUnder5 = "Children Under 5",
    reportsFIC = "FIC (Fully Immunised)",
    reportsFICPercent = "FIC % (Target 90%)",
    reportsCIC = "CIC (Completely Immunised)",
    reportsVaccineDueToday = "Vaccines Due Today",
    reportsVaccineMissed = "Missed Vaccines",
    reportsTB = "TB DOTS",
    reportsTBRegistered = "TB Patients Registered",
    reportsDOTSGood = "DOTS Adherence ≥90%",
    reportsDOTSPoor = "DOTS Adherence <70%",
    reportsDBT = "DBT This Month",
    reportsSchemes = "Government Schemes",
    reportsJSY = "JSY Beneficiaries",
    reportsPMMVY = "PMMVY Beneficiaries",
    reportsNHMActivities = "NHM Activities",

    settingsTitle = "Settings",
    settingsLanguageSection = "Language",
    settingsAppLanguage = "App Language",
    settingsVoiceModels = "Voice Models",
    settingsAppInfo = "App Info",
    settingsLogout = "Logout",
    settingsLogoutTitle = "Logout?",
    settingsLogoutMsg = "Are you sure you want to logout?",
    settingsLogoutYes = "Yes, Logout",
    settingsSelectLanguage = "Select Language",
    settingsCloseBtn = "Close",
)

// ── Kannada ───────────────────────────────────────────────────────────────────

private val Kannada = AppStrings(
    save = "ಉಳಿಸಿ",
    cancel = "ರದ್ದು",
    close = "ಮುಚ್ಚಿ",
    offline = "ಆಫ್‌ಲೈನ್ — ಡೇಟಾ ಉಳಿಸಲಾಗಿದೆ",
    years = "ವರ್ಷ",

    homeMetricVisits = "ಇಂದಿನ\nಭೇಟಿ",
    homeMetricHighRisk = "ಅಧಿಕ\nಅಪಾಯ",
    homeMetricVaccines = "ಲಸಿಕೆ\nಬಾಕಿ",
    homeMetricDots = "DOTS\nಬಾಕಿ",
    homeTotalHouseholds = "ಕುಟುಂಬ",
    homeTotalPatients = "ರೋಗಿಗಳು",
    homeTotalVisitsMonth = "ಈ ತಿಂಗಳು",
    homeHighRiskAlert = "⚠️ %d ಅಧಿಕ ಅಪಾಯ — ಮೊದಲು ಭೇಟಿ ಮಾಡಿ",
    homeWorkplanTitle = "ಇಂದಿನ ಕಾರ್ಯಕ್ರಮ",
    homeAllGood = "ಇಂದು ಎಲ್ಲಾ ಸರಿ!",
    homeVoiceLabel = "🎤  ಧ್ವನಿಯಿಂದ ದಾಖಲು ಮಾಡಿ",
    homeVoiceSub = "ಮನೆ · ರೋಗಿ · ANC · ಲಸಿಕೆ · DOTS",
    homeQuickActions = "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು",
    homeAddFamily = "🏠\nಕುಟುಂಬ ಸೇರಿಸಿ",
    homeViewMap = "🗺️\nನಕ್ಷೆ ನೋಡಿ",
    homeMonthlyReport = "📋\nಮಾಸಿಕ ವರದಿ",
    homeDotsTracker = "💊\nDOTS ಟ್ರ್ಯಾಕರ್",
    tagPregnant = "🤰 ಗರ್ಭಿಣಿ",
    tagChild = "👶 ಶಿಶು",
    tagElderly = "👴 ವೃದ್ಧ",

    householdsTitle = "ಕುಟುಂಬಗಳು",
    householdsSearch = "ಹುಡುಕಿ...",
    householdsEmpty = "ಯಾವುದೇ ಕುಟುಂಬ ಇಲ್ಲ",
    householdsAdd = "ಕುಟುಂಬ ಸೇರಿಸಿ",

    vaccinationTitle = "ಲಸಿಕೆ ಟ್ರ್ಯಾಕರ್",
    vaccineFIC = "✅ FIC: %d ಮಕ್ಕಳು",
    vaccineDueTab = "ಇಂದು ಬಾಕಿ",
    vaccineMissedTab = "ತಪ್ಪಿದ",
    vaccineAllTab = "ಎಲ್ಲಾ",
    vaccineEmpty = "ಲಸಿಕೆ ಬಾಕಿ ಇಲ್ಲ",
    vaccineAgeLabel = "ವಯಸ್ಸು: %d ವರ್ಷ",
    vaccineGiven = "✅ ನೀಡಲಾಗಿದೆ",
    vaccineGiveToday = "⚡ ಇಂದು ನೀಡಿ",
    vaccineMissedDays = "⚠️ ತಪ್ಪಿದೆ (%d ದಿನ)",
    vaccineUpcoming = "📅 ಮುಂದೆ",
    vaccineMarkGiven = "ನೀಡಿದೆ",

    plannerTitle = "ಇಂದಿನ ಯೋಜನೆ",
    plannerEmpty = "ಇಂದು ಯಾವುದೇ ಭೇಟಿ ಇಲ್ಲ",
    plannerSubtitle = "%d ಭೇಟಿ · ಮೊದಲು ಕೆಂಪು, ನಂತರ ಹಳದಿ",
    plannerVisitDone = "✅ ಭೇಟಿ ಆಯಿತು",

    patientPersonalInfo = "ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ",
    patientName = "ಹೆಸರು",
    patientAge = "ವಯಸ್ಸು",
    patientGender = "ಲಿಂಗ",
    patientPhone = "ಫೋನ್",
    patientPregnancy = "🤰 ಗರ್ಭಾವಸ್ಥೆ",
    patientTBDots = "💊 TB / DOTS",
    patientVisitHistory = "ಭೇಟಿ ಇತಿಹಾಸ",
    patientNoVisits = "ಯಾವುದೇ ಭೇಟಿ ಇಲ್ಲ",
    patientReferralNeeded = "⚠️ ರೆಫರಲ್ ಅಗತ್ಯ",

    visitTitle = "ಭೇಟಿ ದಾಖಲಿಸಿ",
    visitVitals = "ವೈಟಲ್ಸ್",
    visitWeight = "ತೂಕ (kg)",
    visitTemp = "ತಾಪಮಾನ (°C)",
    visitPregnancy = "🤰 ಗರ್ಭಾವಸ್ಥೆ ವಿವರ",
    visitIfaToday = "ಇಂದು IFA ಮಾತ್ರೆಗಳು",
    visitFastingGlucose = "ಉಪವಾಸ ಸಕ್ಕರೆ",
    visitIfaProgress = "IFA ಪ್ರಗತಿ: %d / 180",
    visitSymptoms = "ರೋಗಲಕ್ಷಣಗಳು",
    visitFever = "ಜ್ವರ",
    visitCoughDays = "ಕೆಮ್ಮಿನ ದಿನಗಳು",
    visitNotes = "ಕ್ಲಿನಿಕಲ್ ಟಿಪ್ಪಣಿಗಳು",
    visitNotesHint = "ಮೈಕ್ ಒತ್ತಿ ಮಾತಾಡಿ ಅಥವಾ ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ...",
    visitReferral = "ರೆಫರಲ್ ಅಗತ್ಯ",
    visitReferralReason = "ರೆಫರಲ್ ಕಾರಣ",
    visitSave = "ಭೇಟಿ ಉಳಿಸಿ",
    visitNoRisk = "ಯಾವುದೇ ಅಪಾಯ ಕಾರಣ ಕಂಡುಬಂದಿಲ್ಲ.",
    visitOk = "ಸರಿ",

    tbTitle = "TB DOTS ಟ್ರ್ಯಾಕರ್",
    tbEmpty = "TB ರೋಗಿಗಳಿಲ್ಲ",
    tbDotsDue = "⚠️ ಇಂದು DOTS ಬಾಕಿ",
    tbDotsGiven = "✅ DOTS ತೆಗೆದುಕೊಂಡಿದ್ದಾರೆ",
    tbDotsRecord = "DOTS ದಾಖಲಿಸಿ",
    tbCalendar = "ಕ್ಯಾಲೆಂಡರ್",
    tbCalendarTitle = "DOTS ಕ್ಯಾಲೆಂಡರ್",
    tbClose = "ಮುಚ್ಚಿ",

    diaryTitle = "ನನ್ನ ಡೈರಿ",
    diaryEmpty = "ಡೈರಿಯಲ್ಲಿ ಏನಾದರೂ ಬರೆಯಿರಿ",
    diaryNewEntry = "ಹೊಸ ನಮೂದು",
    diaryHint = "ಇಂದಿನ ಬಗ್ಗೆ ಬರೆಯಿರಿ...",
    diarySave = "ಉಳಿಸಿ",
    diaryCancel = "ರದ್ದು",

    reportsTitle = "ಮಾಸಿಕ ವರದಿ",
    reportsPdfDownload = "PDF ಡೌನ್‌ಲೋಡ್",
    reportsCoverage = "ಕವರೇಜ್ ಸಾರಾಂಶ",
    reportsTotalHouseholds = "ಒಟ್ಟು ಕುಟುಂಬ",
    reportsTotalPatients = "ಒಟ್ಟು ರೋಗಿಗಳು",
    reportsVisitsMonth = "ಈ ತಿಂಗಳ ಭೇಟಿ",
    reportsANC = "ANC ಸೇವೆಗಳು",
    reportsPregnant = "ಗರ್ಭಿಣಿ ಮಹಿಳೆಯರು",
    reportsANC1st = "ANC ನೋಂದಣಿ (1st Trimester)",
    reportsANC4Plus = "4+ ANC ಪಡೆದರು",
    reportsTT = "TT2 / Booster ನೀಡಲಾಗಿದೆ",
    reportsIFA180 = "IFA 180 ಪೂರ್ಣ",
    reportsHighRisk = "ಅಧಿಕ ಅಪಾಯ (RED)",
    reportsInstitutional = "ಸಾಂಸ್ಥಿಕ ಹೆರಿಗೆ",
    reportsImmunisation = "UIP ಲಸಿಕೆ",
    reportsUnder5 = "5 ವರ್ಷದೊಳಗಿನ ಮಕ್ಕಳು",
    reportsFIC = "FIC (ಸಂಪೂರ್ಣ ಲಸಿಕೆ)",
    reportsFICPercent = "FIC % (ಗುರಿ 90%)",
    reportsCIC = "CIC (ಸಂಪೂರ್ಣ ವರ್ಗ)",
    reportsVaccineDueToday = "ಇಂದು ಲಸಿಕೆ ಬಾಕಿ",
    reportsVaccineMissed = "ತಪ್ಪಿದ ಲಸಿಕೆ",
    reportsTB = "TB DOTS",
    reportsTBRegistered = "TB ರೋಗಿ ನೋಂದಣಿ",
    reportsDOTSGood = "DOTS ಅನುಸರಣೆ ≥90%",
    reportsDOTSPoor = "DOTS ಅನುಸರಣೆ <70%",
    reportsDBT = "ಈ ತಿಂಗಳ DBT",
    reportsSchemes = "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
    reportsJSY = "JSY ಫಲಾನುಭವಿ",
    reportsPMMVY = "PMMVY ಫಲಾನುಭವಿ",
    reportsNHMActivities = "NHM ಚಟುವಟಿಕೆಗಳು",

    settingsTitle = "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    settingsLanguageSection = "ಭಾಷೆ",
    settingsAppLanguage = "ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆ",
    settingsVoiceModels = "ಧ್ವನಿ ಮಾದರಿ",
    settingsAppInfo = "ಅಪ್ಲಿಕೇಶನ್ ಮಾಹಿತಿ",
    settingsLogout = "ಲಾಗ್ ಔಟ್",
    settingsLogoutTitle = "ಲಾಗ್ ಔಟ್?",
    settingsLogoutMsg = "ನೀವು ನಿಜವಾಗಿಯೂ ಲಾಗ್ ಔಟ್ ಆಗಲು ಬಯಸುತ್ತೀರಾ?",
    settingsLogoutYes = "ಹೌದು, ಲಾಗ್ ಔಟ್",
    settingsSelectLanguage = "ಭಾಷೆ ಆರಿಸಿ",
    settingsCloseBtn = "ಮುಚ್ಚಿ",
)

// ── Accessor ──────────────────────────────────────────────────────────────────

@Composable
fun appStrings(): AppStrings = when (LocalAppLanguage.current) {
    "kn" -> Kannada
    "en" -> English
    else -> Hindi
}
